### ISSUE TITLE
WalletNotReadyError

### ISSUE THREAD

**Issue by niefeian** [demox-labs/aleo-wallet-adapter#5]
WalletNotReadyError
    at LeoWalletAdapter.connect (adapter.ts:177:72)
    at onSubmit (UserIcon.vue:18:6)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at HTMLDivElement.invoker (runtime-dom.esm-bundler.js:339:9)
    
I encountered an error while running on Vue, 127.0.0.1 was accessed normally, but 192.168.2.7 The above error was reported

**Comment by Soonogo** [comment]
Well, I found that it seems to require TLS.
